version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
  db:
    container_name: db
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - mdata:/var/lib/mongodb/data

volumes:
  mdata: {}